/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_bartoszek_jni_ScalarTest */

#ifndef _Included_com_bartoszek_jni_ScalarTest
#define _Included_com_bartoszek_jni_ScalarTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_bartoszek_jni_ScalarTest
 * Method:    multi01
 * Signature: ([Ljava/lang/Double;[Ljava/lang/Double;)Ljava/lang/Double;
 */
JNIEXPORT jobject JNICALL Java_com_bartoszek_jni_ScalarTest_multi01
  (JNIEnv *, jobject, jobjectArray, jobjectArray);

/*
 * Class:     com_bartoszek_jni_ScalarTest
 * Method:    multi02
 * Signature: ([Ljava/lang/Double;)Ljava/lang/Double;
 */
JNIEXPORT jobject JNICALL Java_com_bartoszek_jni_ScalarTest_multi02
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     com_bartoszek_jni_ScalarTest
 * Method:    multi03
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_bartoszek_jni_ScalarTest_multi03
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
